apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    tier: ft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    tier: ft
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: port
    port: 3000
