apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    tier: ft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    tier: ft
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: http
    port: 5050
