apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  labels:
    tier: ft
spec:
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock 
      containers:
      - name: telegraf
        image: telegraf_alpine
        imagePullPolicy: Never
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      terminationGracePeriodSeconds: 30
